### ISSUE TITLE
Fixed Stripe API Keys

### ISSUE THREAD

**Issue by sunny179** [shopware/AppTemplate#5]
As this is payment gateway so client will have their own stripe keys where payment will be directed for all customer orders so we can't keep stripe keys in app > env file. It should be configuration based and our app should fetch configuration settings via Admin API.

Let me know if this makes sense?

**Comment by shyim** [comment]
Hey,

You can call the system-config endpoint of the application and get the config and create with that the stripe client. It would be possible, but you would need to do an API call to the Shopware server always
